dgs:
  graphql:
    schema-locations: "file:../../schema.graphql"
springdoc:
  paths-to-exclude:
    - /graphql
    - /schema.json
  cache:
    disabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jooq:
    sql-dialect: mysql
  devtools:
    restart:
      enabled: true
app:
  aws:
    override-url: ${VITE_AWS_BASE_URL:}
    region: ${AWS_REGION:ap-northeast-1}
    user-pool-id: ${VITE_COGNITO_USER_POOL_ID}
    client-pool-id: ${VITE_COGNITO_USER_CLIENT_POOL_ID}
logging:
  level:
    root: info
management:
  endpoints:
    web.exposure.include: otel
otel:
  exporter:
    otlp:
      endpoint: 'http://otel-collector:4318'
  resource:
    attributes:
      service:
        name: api
