dgs:
  graphql:
    schema-locations: "file:../../schema.graphql"
springdoc:
  paths-to-exclude:
    - /graphql
    - /schema.json
  cache:
    disabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jooq:
    sql-dialect: mysql
app:
  aws:
    override-url: ${VITE_AWS_BASE_URL:}
    region: ${AWS_REGION:ap-northeast-1}
logging:
  level:
    root: debug
