version: '3'
services:
  sqldef:
    build: './docker/sqldef'
    volumes:
      - './docker/sqldef/volume:/volume'
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      - db
  db:
    image: 'mysql:8.3.0'
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - '3306:3306'
  aws-local-cli:
    image: public.ecr.aws/aws-cli/aws-cli:2.15.27
    environment:
      ENDPOINT_URL: http://moto-aws-local:4000
      COGNITO_USER_EMAIL: sample@example.com
      COGNITO_USER_PASSWORD: P@ssword00
    entrypoint: []
    depends_on:
      - moto-aws-local
    volumes:
      - './docker/aws-local-cli/.bin:/aws-local-cli/.bin'
      - './docker/aws-local-cli/.aws:/root/.aws'
      - './docker/aws-local-cli/output:/aws-local-cli/output'
    networks:
      - default
  moto-aws-local:
    image: motoserver/moto:5.0.3
    environment:
      MOTO_PORT: 4000
    ports:
      - '4000:4000'
    networks:
      - default
volumes:
  db-store:
  moto-aws-local:
