version: '3'
services:
  sqldef:
    build: './docker/sqldef'
    volumes:
      - './docker/sqldef/volume:/volume'
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      - db
  db:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      TZ: UTC
    volumes:
      - db-store:/var/lib/postgresql/data
  aws-local-cli:
    image: public.ecr.aws/aws-cli/aws-cli:2.15.28
    environment:
      ENDPOINT_URL: http://moto-aws-local:4000
      COGNITO_USER_EMAIL: sample@example.com
      COGNITO_USER_PASSWORD: P@ssword00
    entrypoint: []
    depends_on:
      - moto-aws-local
    volumes:
      - './docker/aws-local-cli/.bin:/aws-local-cli/.bin'
      - './docker/aws-local-cli/.aws:/root/.aws'
      - './docker/aws-local-cli/output:/aws-local-cli/output'
    networks:
      - default
  moto-aws-local:
    image: motoserver/moto:5.0.3
    environment:
      MOTO_PORT: 4000
    ports:
      - '4000:4000'
    networks:
      - default
volumes:
  db-store:
  moto-aws-local:
