// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignInComponentImport = new FileRoute('/sign-in').createRoute()
const LayoutComponentImport = new FileRoute('/_layout').createRoute()
const LayoutIndexComponentImport = new FileRoute('/_layout/').createRoute()
const LayoutAboutIndexComponentImport = new FileRoute(
  '/_layout/about/',
).createRoute()

// Create/Update Routes

const SignInComponentRoute = SignInComponentImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/sign-in.component'),
    'component',
  ),
})

const LayoutComponentRoute = LayoutComponentImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout.component'),
    'component',
  ),
})

const LayoutIndexComponentRoute = LayoutIndexComponentImport.update({
  path: '/',
  getParentRoute: () => LayoutComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/index.component'),
    'component',
  ),
})

const LayoutAboutIndexComponentRoute = LayoutAboutIndexComponentImport.update({
  path: '/about/',
  getParentRoute: () => LayoutComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/about/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutComponentImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInComponentImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexComponentImport
      parentRoute: typeof LayoutComponentImport
    }
    '/_layout/about/': {
      preLoaderRoute: typeof LayoutAboutIndexComponentImport
      parentRoute: typeof LayoutComponentImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutComponentRoute.addChildren([
    LayoutIndexComponentRoute,
    LayoutAboutIndexComponentRoute,
  ]),
  SignInComponentRoute,
])
