CREATE TABLE "USER"
(
    "ID"         CHAR(36)     NOT NULL,
    "NAME"       VARCHAR(200) NOT NULL,
    "EMAIL"      VARCHAR(320) NOT NULL,
    "CREATED_AT" TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID")
);

CREATE TABLE "ATTENDANCE"
(
    "ATTENDANCE_ID"   CHAR(36)  NOT NULL,
    "USER_ID"         CHAR(36)  NOT NULL,
    "ATTENDANCE_DATE" DATE      NOT NULL,
    "CREATED_AT"      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ATTENDANCE_ID"),
    CONSTRAINT "FKEY_BETWEEN_ATTENDANCE_AND_USER" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID")
        ON DELETE CASCADE
);

CREATE TABLE "ATTENDANCE_RECORD_EVENT"
(
    "ATTENDANCE_RECORD_EVENT_ID" CHAR(36)  NOT NULL,
    "ATTENDANCE_ID"              CHAR(36)  NOT NULL,
    "ATTENDANCE_DATE"            DATE      NOT NULL,
    "RECORD_DATETIME"            TIMESTAMP NOT NULL,
    "EVENT_CREATED_DATETIME"     TIMESTAMP NOT NULL,
    "CREATED_AT"                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ATTENDANCE_RECORD_EVENT_ID"),
    CONSTRAINT "FKEY_BETWEEN_ATTENDANCE_AND_ATTENDANCE_RECORD_EVENT" FOREIGN KEY ("ATTENDANCE_ID") REFERENCES "ATTENDANCE" ("ATTENDANCE_ID")
        ON DELETE CASCADE
);

CREATE TABLE "ATTENDANCE_CORRECT_EVENT"
(
    "ATTENDANCE_CORRECT_EVENT_ID" CHAR(36)  NOT NULL,
    "ATTENDANCE_ID"               CHAR(36)  NOT NULL,
    "ATTENDANCE_RECORD_EVENT_ID"  CHAR(36)  NOT NULL,
    "ATTENDANCE_DATE"             DATE      NOT NULL,
    "CORRECT_DATETIME"            TIMESTAMP NOT NULL,
    "EVENT_CREATED_DATETIME"      TIMESTAMP NOT NULL,
    "CREATED_AT"                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ATTENDANCE_CORRECT_EVENT_ID"),
    CONSTRAINT "FKEY_BETWEEN_ATTENDANCE_AND_ATTENDANCE_CORRECT_EVENT" FOREIGN KEY ("ATTENDANCE_ID") REFERENCES "ATTENDANCE" ("ATTENDANCE_ID"),
    CONSTRAINT "FKEY_ATTENDANCE_RECORD_EVENT_AND_ATTENDANCE_CORRECT_EVENT" FOREIGN KEY ("ATTENDANCE_RECORD_EVENT_ID") REFERENCES "ATTENDANCE_RECORD_EVENT" ("ATTENDANCE_RECORD_EVENT_ID")
        ON DELETE CASCADE
);
