spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jooq:
    sql-dialect: postgres
